name: Build & Push Microservices

on:
  push:
    branches: ["preprod"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - auth
          - profile
          - messenger
          - finance
          - share

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t devops2-g4-${{ matrix.service }}-preprod ./Microservices/${{ matrix.service }}

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names devops2-g4-${{ matrix.service }}-preprod

      - name: Tag & Push Images
        run: |
          VERSION="${{ github.run_number }}"

          # AWS ECR image
          ECR_IMAGE="${{ steps.ecr.outputs.registry }}/devops2-g4-${{ matrix.service }}-preprod:${VERSION}"

          # Tag images
          docker tag devops2-g4-${{ matrix.service }}-preprod $ECR_IMAGE

          # Push images
          docker push $ECR_IMAGE
